# Generated by Django 3.2.4 on 2021-06-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='user_name',
            field=models.TextField(default='John', verbose_name='user_name'),
            preserve_default=False,
        ),
    ]
