# Generated by Django 3.2.4 on 2021-06-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(unique=True, verbose_name='user_id')),
                ('user_name', models.TextField(unique=True, verbose_name='user_name')),
                ('user_is_bot', models.BooleanField(verbose_name='user_id_bot')),
            ],
        ),
    ]
