# Generated by Django 3.2.4 on 2021-06-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='user_is_bot',
            field=models.BooleanField(default=True, verbose_name='user_is_bot'),
            preserve_default=False,
        ),
    ]
