# Generated by Django 3.2.4 on 2021-06-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.TextField(verbose_name='user_name'),
        ),
    ]
